Running testcase: U2.TC-1
Verifikation af at Django pÃ¥ Docker fungerer pÃ¥ lokalmaskine
Linux og Mac
data-volume
mqtt-volume
data-volume
mqtt-volume
*** TEST STEPS ***
Running containers in interactive mode with logging
Please quit with CTRL-C when done viewing output
*** VERIFY NO ERRORS ***
Step 1/15 : FROM python:3.8.0-alpine
 ---> 204216b3821e
Step 2/15 : MAINTAINER Team Web, Janus Bo Andersen
 ---> Using cache
 ---> da61f29561e4
Step 3/15 : WORKDIR /usr/src/webinterface
 ---> Using cache
 ---> 50282d2928f0
Step 4/15 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> e4f005f1c751
Step 5/15 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 2b907d3d4c0f
Step 6/15 : RUN apk update     && apk add postgresql-dev gcc python3-dev musl-dev
 ---> Using cache
 ---> 884d7df53ed2
Step 7/15 : RUN pip install --upgrade pip
 ---> Using cache
 ---> cfb86b683141
Step 8/15 : COPY ./requirements.txt /usr/src/webinterface/requirements.txt
 ---> Using cache
 ---> 745f5226e473
Step 9/15 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 11dc8a9cfdb1
Step 10/15 : COPY ./entrypoint.sh /usr/src/webinterface/entrypoint.sh
 ---> Using cache
 ---> 3881bfff0e17
Step 11/15 : COPY . /usr/src/webinterface/
 ---> a12d7cad35a8
Step 12/15 : RUN chmod 777 /usr/src/webinterface/entrypoint.sh
 ---> Running in cee135611928
Removing intermediate container cee135611928
 ---> 88fe48b78e84
Step 13/15 : RUN adduser -D nonrootuser
 ---> Running in 00051e7c4f38
Removing intermediate container 00051e7c4f38
 ---> fe48412834e6
Step 14/15 : USER nonrootuser
 ---> Running in 760072c0af3f
Removing intermediate container 760072c0af3f
 ---> eca6c86c02ca
Step 15/15 : ENTRYPOINT ["/usr/src/webinterface/entrypoint.sh"]
 ---> Running in 58669e245ba8
Removing intermediate container 58669e245ba8
 ---> 2f0aa27c3e70

Successfully built 2f0aa27c3e70
Successfully tagged server-setup_webinterface:latest
Attaching to server-setup_mqtt_1, server-setup_db_1, server-setup_nginx_1, server-setup_webinterface_1
[36mmqtt_1          |[0m 1574950972: mosquitto version 1.6.7 starting
[33mdb_1            |[0m The files belonging to this database system will be owned by user "postgres".
[36mmqtt_1          |[0m 1574950972: Config loaded from /mosquitto/config/mosquitto.conf.
[33mdb_1            |[0m This user must also own the server process.
[36mmqtt_1          |[0m 1574950972: Opening ipv4 listen socket on port 1883.
[36mmqtt_1          |[0m 1574950972: Opening ipv6 listen socket on port 1883.
[33mdb_1            |[0m 
[35mwebinterface_1  |[0m Waiting for PostgreSQL service before starting Django...
[33mdb_1            |[0m The database cluster will be initialized with locale "en_US.utf8".
[33mdb_1            |[0m The default database encoding has accordingly been set to "UTF8".
[33mdb_1            |[0m The default text search configuration will be set to "english".
[33mdb_1            |[0m 
[33mdb_1            |[0m Data page checksums are disabled.
[33mdb_1            |[0m 
[33mdb_1            |[0m fixing permissions on existing directory /var/lib/postgresql/data ... ok
[33mdb_1            |[0m creating subdirectories ... ok
[33mdb_1            |[0m selecting dynamic shared memory implementation ... posix
[33mdb_1            |[0m selecting default max_connections ... 100
[33mdb_1            |[0m selecting default shared_buffers ... 128MB
[33mdb_1            |[0m selecting default time zone ... UTC
[33mdb_1            |[0m creating configuration files ... ok
[33mdb_1            |[0m running bootstrap script ... ok
[33mdb_1            |[0m performing post-bootstrap initialization ... sh: locale: not found
[33mdb_1            |[0m 2019-11-28 14:22:53.480 UTC [26] WARNING:  no usable system locales were found
[33mdb_1            |[0m ok
[33mdb_1            |[0m syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
[33mdb_1            |[0m You can change this by editing pg_hba.conf or using the option -A, or
[33mdb_1            |[0m --auth-local and --auth-host, the next time you run initdb.
[33mdb_1            |[0m ok
[33mdb_1            |[0m 
[33mdb_1            |[0m 
[33mdb_1            |[0m Success. You can now start the database server using:
[33mdb_1            |[0m 
[33mdb_1            |[0m     pg_ctl -D /var/lib/postgresql/data -l logfile start
[33mdb_1            |[0m 
[33mdb_1            |[0m waiting for server to start....2019-11-28 14:22:53.977 UTC [30] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
[33mdb_1            |[0m 2019-11-28 14:22:53.981 UTC [30] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[33mdb_1            |[0m 2019-11-28 14:22:54.009 UTC [31] LOG:  database system was shut down at 2019-11-28 14:22:53 UTC
[33mdb_1            |[0m 2019-11-28 14:22:54.015 UTC [30] LOG:  database system is ready to accept connections
[33mdb_1            |[0m  done
[33mdb_1            |[0m server started
[33mdb_1            |[0m CREATE DATABASE
[33mdb_1            |[0m 
[33mdb_1            |[0m 
[33mdb_1            |[0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
[33mdb_1            |[0m 
[33mdb_1            |[0m waiting for server to shut down....2019-11-28 14:22:54.204 UTC [30] LOG:  received fast shutdown request
[33mdb_1            |[0m 2019-11-28 14:22:54.208 UTC [30] LOG:  aborting any active transactions
[33mdb_1            |[0m 2019-11-28 14:22:54.209 UTC [30] LOG:  background worker "logical replication launcher" (PID 37) exited with exit code 1
[33mdb_1            |[0m 2019-11-28 14:22:54.210 UTC [32] LOG:  shutting down
[33mdb_1            |[0m 2019-11-28 14:22:54.241 UTC [30] LOG:  database system is shut down
[33mdb_1            |[0m  done
[33mdb_1            |[0m server stopped
[33mdb_1            |[0m 
[33mdb_1            |[0m PostgreSQL init process complete; ready for start up.
[33mdb_1            |[0m 
[33mdb_1            |[0m 2019-11-28 14:22:54.314 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
[33mdb_1            |[0m 2019-11-28 14:22:54.314 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[33mdb_1            |[0m 2019-11-28 14:22:54.315 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[35mwebinterface_1  |[0m PostgreSQL started... Starting Django now.
[33mdb_1            |[0m 2019-11-28 14:22:54.321 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[33mdb_1            |[0m 2019-11-28 14:22:54.340 UTC [41] LOG:  database system was shut down at 2019-11-28 14:22:54 UTC
[33mdb_1            |[0m 2019-11-28 14:22:54.346 UTC [1] LOG:  database system is ready to accept connections
[35mwebinterface_1  |[0m crontab: must be suid to work properly
[35mwebinterface_1  |[0m   adding cronjob: (8f4f038e2cf4dbf8ff8eaeb1337b0452) -> ('*/1 * * * *', 'database_poc.cron.Database_clean_up')
[35mwebinterface_1  |[0m crontab: must be suid to work properly
[35mwebinterface_1  |[0m No changes detected in app 'database_poc'
[35mwebinterface_1  |[0m Operations to perform:
[35mwebinterface_1  |[0m   Apply all migrations: admin, auth, contenttypes, database_poc, sessions
[35mwebinterface_1  |[0m Running migrations:
[35mwebinterface_1  |[0m   Applying contenttypes.0001_initial... OK
[35mwebinterface_1  |[0m   Applying auth.0001_initial... OK
[35mwebinterface_1  |[0m   Applying admin.0001_initial... OK
[35mwebinterface_1  |[0m   Applying admin.0002_logentry_remove_auto_add... OK
[35mwebinterface_1  |[0m   Applying admin.0003_logentry_add_action_flag_choices... OK
[35mwebinterface_1  |[0m   Applying contenttypes.0002_remove_content_type_name... OK
[35mwebinterface_1  |[0m   Applying auth.0002_alter_permission_name_max_length... OK
[35mwebinterface_1  |[0m   Applying auth.0003_alter_user_email_max_length... OK
[35mwebinterface_1  |[0m   Applying auth.0004_alter_user_username_opts... OK
[35mwebinterface_1  |[0m   Applying auth.0005_alter_user_last_login_null... OK
[35mwebinterface_1  |[0m   Applying auth.0006_require_contenttypes_0002... OK
[35mwebinterface_1  |[0m   Applying auth.0007_alter_validators_add_error_messages... OK
[35mwebinterface_1  |[0m   Applying auth.0008_alter_user_username_max_length... OK
[35mwebinterface_1  |[0m   Applying auth.0009_alter_user_last_name_max_length... OK
[35mwebinterface_1  |[0m   Applying auth.0010_alter_group_name_max_length... OK
[35mwebinterface_1  |[0m   Applying auth.0011_update_proxy_permissions... OK
[35mwebinterface_1  |[0m   Applying database_poc.0001_initial... OK
[35mwebinterface_1  |[0m   Applying sessions.0001_initial... OK
[35mwebinterface_1  |[0m Watching for file changes with StatReloader
[35mwebinterface_1  |[0m Performing system checks...
[35mwebinterface_1  |[0m 
[35mwebinterface_1  |[0m System check identified no issues (0 silenced).
[35mwebinterface_1  |[0m November 28, 2019 - 14:22:58
[35mwebinterface_1  |[0m Django version 2.2.7, using settings 'webinterface.settings'
[35mwebinterface_1  |[0m Starting development server at http://0.0.0.0:8000/
[35mwebinterface_1  |[0m Quit the server with CONTROL-C.
[35mwebinterface_1  |[0m Not Found: /
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:05] "GET / HTTP/1.1" 404 2032
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:10] "GET /test/ HTTP/1.1" 200 372
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:11] "GET /test/datainput/ HTTP/1.1" 200 560
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:13] "POST /test/datainput/ HTTP/1.1" 302 0
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:13] "GET /test/ HTTP/1.1" 200 372
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:13] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:16] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:17] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:17] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:17] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:18] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:18] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:19] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:19] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:20] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:20] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:21] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:21] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:50] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:23:51] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:09] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:10] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:11] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:12] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:12] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:13] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:13] "GET /test/dataoutput/ HTTP/1.1" 200 529
[35mwebinterface_1  |[0m [28/Nov/2019 14:24:14] "GET /test/dataoutput/ HTTP/1.1" 200 529
Gracefully stopping... (press Ctrl+C again to force)
***Vi starter lige forfra***
*** RE-STARTING SERVICES AND BROWSER ***
